name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated version
      - uses: actions/setup-java@v4  # Updated version
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: zygisk-imgui-modmenu
          path: out/magisk_module_release/
